// ─── N1 Vocabulary ────────────────────────────────────────────────────────────
// Sourced from Shin Kanzen Master N1, So-Matome N1, and JMdict/JLPT frequency
// lists filtered to words not appearing in N2–N5 core lists.
// frequency_rank: lower = higher frequency within N1 corpus.
// ──────────────────────────────────────────────────────────────────────────────

export type VocabSeed = [
  word: string,
  reading: string,
  meaning: string,
  example_jp: string,
  example_en: string,
  category: string,
  frequency_rank: number,
];

export type GrammarSeed = [
  pattern: string,
  meaning: string,
  usage: string,
  example_jp: string,
  example_en: string,
  notes: string,
  formality_level: string,
];

// ─── VOCABULARY ───────────────────────────────────────────────────────────────

export const vocabulary: VocabSeed[] = [
  // ── 副詞・接続詞 (Adverbs / Conjunctions) ───────────────────────────────────
  ['漸く',     'ようやく',   'Finally; at last; barely',
   'ようやく全員の同意が得られた。', 'We finally obtained everyone\'s consent.', '副詞', 1],
  ['概ね',     'おおむね',   'Generally; for the most part; in broad outline',
   '作業は概ね順調に進んでいる。', 'The work is generally progressing smoothly.', '副詞', 2],
  ['些か',     'いささか',   'A little; somewhat; slightly (formal)',
   '彼の態度はいささか失礼だった。', 'His attitude was somewhat rude.', '副詞', 3],
  ['専ら',     'もっぱら',   'Exclusively; solely; entirely',
   '休日は専ら読書に費やす。', 'I spend holidays exclusively reading.', '副詞', 4],
  ['敢えて',   'あえて',     'Dare to; deliberately; expressly',
   'あえてその困難な課題に挑んだ。', 'I dared to take on that difficult task.', '副詞', 5],
  ['殊更',     'ことさら',   'Especially; deliberately; on purpose',
   'ことさら騒ぎ立てる必要はない。', 'There is no need to deliberately make a fuss.', '副詞', 6],
  ['概して',   'がいして',   'Generally; on the whole; as a rule',
   '概して若者は変化を好む。', 'Generally, young people like change.', '副詞', 7],
  ['却って',   'かえって',   'On the contrary; rather; all the more',
   '叱ったら、かえって反発した。', 'When I scolded him, he reacted with even more defiance.', '副詞', 8],
  ['尤も',     'もっとも',   'Indeed; of course; naturally; however (conjunction)',
   'もっとも、例外もある。', 'However, there are exceptions.', '副詞', 9],
  ['徒に',     'いたずらに', 'In vain; uselessly; idly; without purpose',
   '時間をいたずらに過ごすべきではない。', 'One should not spend time idly.', '副詞', 10],
  ['寧ろ',     'むしろ',     'Rather; instead; preferably',
   'むしろ直接話した方がいい。', 'It would be better to speak directly instead.', '副詞', 11],
  ['悉く',     'ことごとく', 'All; entirely; without exception',
   '計画はことごとく失敗に終わった。', 'All the plans ended in failure.', '副詞', 12],
  ['敢然と',   'かんぜんと', 'Resolutely; boldly; courageously',
   '困難に敢然と立ち向かった。', 'He resolutely faced the difficulties.', '副詞', 13],
  ['蓋し',     'けだし',     'Indeed; truly; perhaps (literary/formal)',
   'けだし、彼は時代の先駆者だろう。', 'Indeed, he is perhaps a pioneer of the age.', '副詞', 14],
  ['尚且つ',   'なおかつ',   'Moreover; furthermore; and yet; on top of that',
   '有能で、なおかつ謙虚な人物だ。', 'He is capable and moreover humble.', '接続詞', 15],
  ['況して',   'まして',     'Much more; all the more; let alone',
   '大人でも難しい。まして子供には無理だ。', 'It is difficult even for adults, let alone children.', '副詞', 16],
  ['爾来',     'じらい',     'Since then; from that time on; thereafter',
   '爾来、二人は会っていない。', 'Since then, the two have not met.', '副詞', 17],
  ['仮令',     'たとえ',     'Even if; no matter what; though',
   'たとえ失敗しても、諦めない。', 'Even if I fail, I will not give up.', '副詞', 18],
  ['延いては', 'ひいては',   'And by extension; ultimately; in the long run',
   '個人の幸福は、ひいては社会全体の幸福につながる。', 'Individual happiness ultimately connects to the happiness of society as a whole.', '副詞', 19],
  ['猶更',     'なおさら',   'Even more; all the more so; especially',
   '高齢者にとって、健康はなおさら大切だ。', 'For the elderly, health is all the more important.', '副詞', 20],

  // ── 名詞：抽象・論理 (Abstract / Logical Nouns) ─────────────────────────────
  ['齟齬',     'そご',       'Discrepancy; inconsistency; contradiction; mismatch',
   '両者の認識に齟齬が生じた。', 'A discrepancy arose between the two parties\' understanding.', '名詞', 21],
  ['逡巡',     'しゅんじゅん','Hesitation; vacillation; wavering',
   '逡巡の末に、彼は断った。', 'After much hesitation, he declined.', '名詞', 22],
  ['顛末',     'てんまつ',   'Full account; whole story; circumstances; particulars',
   '事件の顛末を上司に報告した。', 'I reported the full account of the incident to my superior.', '名詞', 23],
  ['俯瞰',     'ふかん',     'Bird\'s-eye view; overview; seeing the whole picture',
   '問題を俯瞰的に捉える必要がある。', 'It is necessary to grasp the problem from a bird\'s-eye view.', '名詞', 24],
  ['恣意',     'しい',       'Arbitrariness; willfulness; self-indulgence',
   '恣意的な解釈は許されない。', 'Arbitrary interpretation is not permitted.', '名詞', 25],
  ['乖離',     'かいり',     'Divergence; separation; gap; discrepancy',
   '理想と現実の乖離が問題だ。', 'The divergence between ideal and reality is a problem.', '名詞', 26],
  ['払拭',     'ふっしょく', 'Wiping out; dispelling; clearing away',
   '不信感を払拭するのは容易ではない。', 'It is not easy to dispel distrust.', '名詞', 27],
  ['逼迫',     'ひっぱく',   'Urgency; pressing need; being hard-pressed',
   '財政が逼迫している状況だ。', 'The financial situation is pressing.', '名詞', 28],
  ['斡旋',     'あっせん',   'Mediation; arrangement; good offices; intercession',
   '就職を斡旋してもらった。', 'I had them arrange a job for me.', '名詞', 29],
  ['捏造',     'ねつぞう',   'Fabrication; falsification; concoction',
   '証拠の捏造が発覚した。', 'The fabrication of evidence was discovered.', '名詞', 30],
  ['蹉跌',     'さてつ',     'Failure; setback; stumble; miscarriage',
   '計画は蹉跌を来した。', 'The plan met with a setback.', '名詞', 31],
  ['徒労',     'とろう',     'Wasted effort; futile labor; fruitless work',
   '彼の努力は徒労に終わった。', 'His efforts ended in vain.', '名詞', 32],
  ['辻褄',     'つじつま',   'Coherence; consistency; logical connection',
   '話の辻褄が合わない。', 'The story doesn\'t add up.', '名詞', 33],
  ['杞憂',     'きゆう',     'Needless anxiety; groundless worry; unfounded fear',
   '心配は杞憂に終わった。', 'The worry turned out to be needless.', '名詞', 34],
  ['僥倖',     'ぎょうこう', 'Windfall; stroke of luck; happy coincidence',
   '助かったのは僥倖に過ぎない。', 'Being saved was nothing more than a windfall.', '名詞', 35],
  ['忸怩',     'じくじ',     'Feeling ashamed; self-reproach; mortification',
   '忸怩たる思いで謝罪した。', 'I apologized with a feeling of shame.', '名詞', 36],
  ['矜持',     'きょうじ',   'Pride; dignity; self-respect; sense of honor',
   '職人としての矜持を持って仕事をする。', 'I work with pride as a craftsman.', '名詞', 37],
  ['懊悩',     'おうのう',   'Anguish; distress; mental agony; torment',
   '懊悩の日々を過ごした。', 'I spent days in anguish.', '名詞', 38],
  ['慟哭',     'どうこく',   'Bitter crying; wailing; violent weeping',
   '遺族は慟哭した。', 'The bereaved family wailed in grief.', '名詞', 39],
  ['嚆矢',     'こうし',     'Beginning; inception; origin; pioneering (lit. signal arrow)',
   'これが近代医学の嚆矢となった。', 'This became the beginning of modern medicine.', '名詞', 40],
  ['邂逅',     'かいこう',   'Chance meeting; fortuitous encounter; serendipitous reunion',
   '旧友との邂逅を喜んだ。', 'I was glad to have a chance meeting with an old friend.', '名詞', 41],
  ['蹂躙',     'じゅうりん', 'Trampling underfoot; violation; infringement',
   '人権の蹂躙は許されない。', 'Trampling on human rights is not permitted.', '名詞', 42],
  ['膠着',     'こうちゃく', 'Stalemate; deadlock; adhesion; being bogged down',
   '交渉は膠着状態に陥った。', 'The negotiations fell into a deadlock.', '名詞', 43],
  ['頓挫',     'とんざ',     'Setback; sudden check; coming to a halt; collapse',
   '計画は資金不足で頓挫した。', 'The plan collapsed due to lack of funds.', '名詞', 44],
  ['更迭',     'こうてつ',   'Reshuffle; replacement; dismissal (of an official)',
   '大臣が更迭された。', 'The minister was replaced.', '名詞', 45],
  ['弾劾',     'だんがい',   'Impeachment; censure; denunciation',
   '大統領の弾劾裁判が始まった。', 'The impeachment trial of the president began.', '名詞', 46],
  ['粛清',     'しゅくせい', 'Purge; liquidation; eliminating dissidents',
   '政治的粛清が行われた。', 'A political purge was carried out.', '名詞', 47],
  ['忌憚',     'きたん',     'Reserve; hesitation; restraint; reluctance',
   '忌憚のない意見を求めた。', 'I sought frank opinions without reservation.', '名詞', 48],
  ['陳情',     'ちんじょう', 'Petition; appeal; representation; lobbying',
   '住民が市長に陳情した。', 'The residents petitioned the mayor.', '名詞', 49],
  ['諮問',     'しもん',     'Consultation; inquiry; referring for advice',
   '委員会への諮問事項を決めた。', 'We decided on the matters to refer to the committee.', '名詞', 50],

  // ── 名詞：感情・心理 (Emotion / Psychology) ────────────────────────────────
  ['哀愁',     'あいしゅう', 'Pathos; melancholy; sadness; wistfulness',
   '秋の夕暮れに哀愁を感じる。', 'I feel a sense of melancholy at autumn dusk.', '名詞', 51],
  ['郷愁',     'きょうしゅう','Nostalgia; homesickness; longing for the past',
   '故郷の景色に郷愁を覚える。', 'The scenery of my hometown evokes nostalgia.', '名詞', 52],
  ['恍惚',     'こうこつ',   'Ecstasy; rapture; trance; being enraptured',
   '美しい音楽に恍惚とした。', 'I was enraptured by the beautiful music.', '名詞', 53],
  ['焦燥',     'しょうそう', 'Impatience; fretfulness; frustration; anxiety',
   '焦燥感に駆られて行動した。', 'I acted driven by a sense of impatience.', '名詞', 54],
  ['嫌悪',     'けんお',     'Hatred; disgust; aversion; loathing',
   '暴力に対する嫌悪感を覚えた。', 'I felt a sense of disgust toward violence.', '名詞', 55],
  ['憤慨',     'ふんがい',   'Indignation; resentment; righteous anger',
   '不当な扱いに憤慨した。', 'I was indignant at the unfair treatment.', '名詞', 56],
  ['安堵',     'あんど',     'Relief; reassurance; peace of mind',
   '無事を確認して安堵した。', 'I felt relieved after confirming everyone was safe.', '名詞', 57],
  ['欣喜',     'きんき',     'Great joy; jubilation; elation',
   '合格の知らせに欣喜した。', 'I was overjoyed at the news of passing.', '名詞', 58],
  ['憂愁',     'ゆうしゅう', 'Gloom; melancholy; despondency',
   '憂愁に沈む日々が続いた。', 'Days of sinking into gloom continued.', '名詞', 59],
  ['昂揚',     'こうよう',   'Elation; exaltation; uplift; heightening',
   '士気の昂揚を図った。', 'We tried to boost morale.', '名詞', 60],
  ['卑屈',     'ひくつ',     'Servile; cringing; abject; self-deprecating',
   '卑屈な態度を取る必要はない。', 'There is no need to take a servile attitude.', '名詞', 61],
  ['嫉妬',     'しっと',     'Jealousy; envy; jealous feeling',
   '彼の成功を嫉妬する人もいた。', 'There were also people who were jealous of his success.', '名詞', 62],

  // ── 名詞：社会・政治 (Society / Politics) ───────────────────────────────────
  ['格差',     'かくさ',     'Gap; disparity; inequality; differential',
   '経済格差の拡大が問題視されている。', 'The widening of economic disparity is being seen as a problem.', '名詞', 63],
  ['癒着',     'ゆちゃく',   'Adhesion; corrupt connection; collusion; cronyism',
   '政官の癒着が批判された。', 'The collusion between politicians and bureaucrats was criticized.', '名詞', 64],
  ['弊害',     'へいがい',   'Harmful effect; evil practice; ill; adverse effect',
   '官僚主義の弊害が現れた。', 'The harmful effects of bureaucratism appeared.', '名詞', 65],
  ['慣行',     'かんこう',   'Customary practice; established usage; conventional way',
   '業界の慣行に従った。', 'We followed the industry\'s established practices.', '名詞', 66],
  ['規範',     'きはん',     'Norm; standard; model; criterion; code of conduct',
   '社会的規範を守ることが大切だ。', 'It is important to observe social norms.', '名詞', 67],
  ['抗争',     'こうそう',   'Conflict; strife; feud; dispute',
   '派閥間の抗争が続いた。', 'The conflict between factions continued.', '名詞', 68],
  ['軋轢',     'あつれき',   'Friction; discord; strife; conflict (between people)',
   '両者の間に軋轢が生じた。', 'Friction arose between the two parties.', '名詞', 69],
  ['確執',     'かくしつ',   'Feud; discord; deep-seated conflict; enmity',
   '長年の確執が解消された。', 'A long-standing feud was resolved.', '名詞', 70],
  ['葛藤',     'かっとう',   'Conflict; discord; complication; inner struggle',
   '心の中で葛藤を感じた。', 'I felt an inner conflict.', '名詞', 71],
  ['施策',     'しさく',     'Policy; measure; plan of action',
   '福祉施策の拡充を求めた。', 'We demanded the expansion of welfare measures.', '名詞', 72],
  ['談合',     'だんごう',   'Bid-rigging; collusion; prior consultation',
   '談合の疑いで調査が入った。', 'An investigation came in due to suspicion of bid-rigging.', '名詞', 73],
  ['排斥',     'はいせき',   'Exclusion; expulsion; ostracism; rejection',
   '外国人の排斥運動が起きた。', 'A movement to exclude foreigners arose.', '名詞', 74],

  // ── 名詞：経済 (Economics) ──────────────────────────────────────────────────
  ['相殺',     'そうさい',   'Offset; cancellation; balancing out',
   '利益と損失が相殺された。', 'The gains and losses cancelled each other out.', '名詞', 75],
  ['担保',     'たんぽ',     'Collateral; security; guarantee; pledge',
   '不動産を担保に融資を受けた。', 'I received a loan using real estate as collateral.', '名詞', 76],
  ['逓減',     'ていげん',   'Gradual decrease; progressive reduction; diminishing returns',
   '限界効用は逓減する。', 'Marginal utility diminishes.', '名詞', 77],
  ['逓増',     'ていぞう',   'Gradual increase; progressive increase',
   '生産量は逓増した。', 'The production volume gradually increased.', '名詞', 78],
  ['騰貴',     'とうき',     'Rise in prices; soaring prices; surge',
   '物価の騰貴が続いている。', 'The rise in prices is continuing.', '名詞', 79],
  ['滞納',     'たいのう',   'Non-payment; delinquency; default; arrears',
   '税金を滞納した。', 'I defaulted on paying taxes.', '名詞', 80],

  // ── 名詞：法律 (Law) ────────────────────────────────────────────────────────
  ['控訴',     'こうそ',     'Appeal (to a higher court); lodging an appeal',
   '判決を不服として控訴した。', 'I appealed, dissatisfied with the verdict.', '名詞', 81],
  ['上告',     'じょうこく', 'Final appeal; cassation; appeal to the supreme court',
   '最高裁に上告した。', 'We filed a final appeal to the Supreme Court.', '名詞', 82],
  ['求刑',     'きゅうけい', 'Demand for a sentence (by prosecution); prosecutorial demand',
   '検察は懲役10年を求刑した。', 'The prosecution demanded a sentence of 10 years.', '名詞', 83],
  ['猶予',     'ゆうよ',     'Grace period; postponement; reprieve; deferment',
   '執行猶予付きの判決が下された。', 'A verdict with a suspended sentence was handed down.', '名詞', 84],
  ['免責',     'めんせき',   'Exemption from liability; immunity; indemnification',
   '免責条項を確認した。', 'I confirmed the exemption clause.', '名詞', 85],
  ['論駁',     'ろんばく',   'Refutation; rebuttal; confutation',
   '相手の主張を論駁した。', 'I refuted the other party\'s argument.', '名詞', 86],

  // ── 名詞：学術・哲学 (Academic / Philosophy) ────────────────────────────────
  ['演繹',     'えんえき',   'Deduction; deductive reasoning',
   '演繹法で結論を導いた。', 'I drew a conclusion using deductive reasoning.', '名詞', 87],
  ['帰納',     'きのう',     'Induction; inductive reasoning',
   '帰納法による仮説を立てた。', 'I formulated a hypothesis using inductive reasoning.', '名詞', 88],
  ['実証',     'じっしょう', 'Empirical proof; demonstration; verification by evidence',
   '理論を実証する実験を行った。', 'We conducted an experiment to empirically verify the theory.', '名詞', 89],
  ['弁証法',   'べんしょうほう','Dialectics; dialectical method',
   'ヘーゲルの弁証法を学んだ。', 'I studied Hegel\'s dialectics.', '名詞', 90],
  ['形而上学', 'けいじじょうがく','Metaphysics; metaphysical studies',
   '形而上学的な問いに向き合う。', 'I confront metaphysical questions.', '名詞', 91],
  ['認識論',   'にんしきろん','Epistemology; theory of knowledge',
   '認識論は知識の本質を問う。', 'Epistemology questions the nature of knowledge.', '名詞', 92],
  ['本質',     'ほんしつ',   'Essence; true nature; quintessence',
   '物事の本質を見極める。', 'I discern the true nature of things.', '名詞', 93],
  ['普遍',     'ふへん',     'Universal; general; omnipresence',
   '普遍的な真理を探求する。', 'I pursue universal truths.', '名詞', 94],
  ['真髄',     'しんずい',   'Essence; quintessence; marrow; pith',
   '武道の真髄を学ぶ。', 'I learn the essence of martial arts.', '名詞', 95],
  ['形骸',     'けいがい',   'Empty shell; mere form; skeleton without substance',
   '制度が形骸化した。', 'The system became a mere shell.', '名詞', 96],

  // ── 名詞：自然・環境 (Nature / Environment) ─────────────────────────────────
  ['荒廃',     'こうはい',   'Devastation; ruin; desolation; decay',
   '戦争による荒廃から復興した。', 'We recovered from the devastation of war.', '名詞', 97],
  ['枯渇',     'こかつ',     'Exhaustion; drying up; depletion; running dry',
   '水資源の枯渇が懸念される。', 'There are concerns about the depletion of water resources.', '名詞', 98],
  ['豊穣',     'ほうじょう', 'Abundance; fertility; fruitfulness; bounty',
   '豊穣な大地に感謝する。', 'I am grateful for the bountiful earth.', '名詞', 99],
  ['蔓延',     'まんえん',   'Spread; proliferation; diffusion; rampancy',
   '感染症が蔓延した。', 'The infectious disease spread.', '名詞', 100],
  ['氾濫',     'はんらん',   'Flood; overflow; inundation; proliferation',
   '河川が氾濫した。', 'The river flooded.', '名詞', 101],
  ['侵食',     'しんしょく', 'Erosion; corrosion; encroachment; eating away',
   '海岸線の侵食が進んでいる。', 'Coastal erosion is progressing.', '名詞', 102],
  ['堆積',     'たいせき',   'Accumulation; deposit; sedimentation; piling up',
   '長年の堆積物が発見された。', 'A deposit accumulated over many years was discovered.', '名詞', 103],
  ['喧騒',     'けんそう',   'Clamor; uproar; bustle; hustle and bustle',
   '都会の喧騒を離れて静養した。', 'I rested away from the bustle of the city.', '名詞', 104],
  ['静寂',     'せいじゃく', 'Silence; stillness; tranquility; hushed quiet',
   '深夜の静寂に包まれた。', 'I was enveloped in the silence of late night.', '名詞', 105],
  ['黎明',     'れいめい',   'Dawn; daybreak; beginning (of an era)',
   '民主主義の黎明期にあった。', 'It was the dawn of democracy.', '名詞', 106],

  // ── 名詞：身体・医療 (Body / Medicine) ──────────────────────────────────────
  ['痙攣',     'けいれん',   'Convulsion; cramp; spasm; seizure',
   '高熱で痙攣を起こした。', 'He had a convulsion from a high fever.', '名詞', 107],
  ['倦怠',     'けんたい',   'Languor; fatigue; lassitude; listlessness',
   '慢性的な倦怠感に悩んでいる。', 'I am suffering from chronic fatigue.', '名詞', 108],
  ['麻痺',     'まひ',       'Paralysis; numbness; palsy; breakdown',
   '交通機関が麻痺した。', 'Transportation was paralyzed.', '名詞', 109],
  ['萎縮',     'いしゅく',   'Atrophy; withering; shrinkage; shrinking back',
   '筋肉が萎縮してしまった。', 'The muscles atrophied.', '名詞', 110],
  ['硬直',     'こうちょく', 'Stiffness; rigidity; inflexibility',
   '組織の硬直化が問題だ。', 'The rigidity of the organization is a problem.', '名詞', 111],

  // ── 名詞：文学・芸術 (Literature / Arts) ────────────────────────────────────
  ['陶酔',     'とうすい',   'Intoxication; fascination; rapture; being captivated',
   '音楽に陶酔した。', 'I was enraptured by the music.', '名詞', 112],
  ['余韻',     'よいん',     'Lingering sound; reverberation; aftertaste; lingering effect',
   '演奏の余韻に浸った。', 'I savored the lingering effect of the performance.', '名詞', 113],
  ['情趣',     'じょうしゅ', 'Taste; elegance; sentiment; romantic feeling',
   '日本庭園の情趣を楽しんだ。', 'I enjoyed the elegance of the Japanese garden.', '名詞', 114],
  ['風情',     'ふぜい',     'Elegance; taste; appearance; atmosphere; air',
   '古い町並みに風情がある。', 'The old townscape has a special atmosphere.', '名詞', 115],
  ['余情',     'よじょう',   'Lingering sentiment; aftertaste; emotional resonance',
   '読後の余情がいつまでも続く。', 'The lingering sentiment after reading continues for a long time.', '名詞', 116],
  ['含蓄',     'がんちく',   'Implication; depth of meaning; content; significance',
   '含蓄のある言葉だ。', 'It is a meaningful saying.', '名詞', 117],
  ['婉曲',     'えんきょく', 'Roundabout; circumlocutory; euphemistic; indirect',
   '婉曲な表現で断った。', 'I declined using a roundabout expression.', '名詞', 118],
  ['諷刺',     'ふうし',     'Satire; irony; sarcasm; caricature',
   '政治家への諷刺が込められた作品だ。', 'It is a work containing satire of politicians.', '名詞', 119],
  ['象徴',     'しょうちょう','Symbol; emblem; representation',
   '鳩は平和の象徴だ。', 'The dove is a symbol of peace.', '名詞', 120],

  // ── 名詞：時間・変化 (Time / Change) ────────────────────────────────────────
  ['刹那',     'せつな',     'Moment; instant (Buddhist); brief interval',
   'その刹那、稲妻が走った。', 'In that instant, lightning flashed.', '名詞', 121],
  ['恒久',     'こうきゅう', 'Permanent; everlasting; perpetual; lasting',
   '恒久的な平和を望む。', 'We desire everlasting peace.', '名詞', 122],
  ['瞬時',     'しゅんじ',   'Instant; moment; flash; split second',
   '瞬時に状況を判断した。', 'I judged the situation in an instant.', '名詞', 123],

  // ── 名詞：思考・認識 (Thought / Cognition) ──────────────────────────────────
  ['洞察',     'どうさつ',   'Insight; discernment; penetrating observation',
   '鋭い洞察力を持つ人物だ。', 'He is a person with sharp insight.', '名詞', 124],
  ['直観',     'ちょっかん', 'Intuition; direct perception',
   '直観的に危険を感じた。', 'I intuitively sensed danger.', '名詞', 125],
  ['憶測',     'おくそく',   'Conjecture; speculation; surmise; guesswork',
   '憶測で物事を判断すべきではない。', 'One should not judge things based on speculation.', '名詞', 126],
  ['斟酌',     'しんしゃく', 'Consideration; discretion; making allowances; taking into account',
   '事情を斟酌して判断する。', 'I judge while making allowances for the circumstances.', '名詞', 127],
  ['熟慮',     'じゅくりょ', 'Careful consideration; deliberation; pondering',
   '熟慮の末に決断した。', 'I made the decision after careful deliberation.', '名詞', 128],
  ['示唆',     'しさ',       'Suggestion; hint; implication; intimation',
   '研究結果はいくつかの点を示唆している。', 'The research results suggest several points.', '名詞', 129],
  ['論拠',     'ろんきょ',   'Grounds for argument; basis; rationale; evidence',
   '主張の論拠を示した。', 'I presented the grounds for my argument.', '名詞', 130],

  // ── 名詞：倫理・宗教 (Ethics / Religion) ────────────────────────────────────
  ['倫理',     'りんり',     'Ethics; morals; moral principles',
   '生命倫理の問題が問われている。', 'The question of bioethics is being raised.', '名詞', 131],
  ['無常',     'むじょう',   'Impermanence; transience; mutability (Buddhist)',
   '人の世の無常を感じた。', 'I felt the impermanence of human life.', '名詞', 132],
  ['輪廻',     'りんね',     'Reincarnation; transmigration; samsara (Buddhist)',
   '輪廻転生を信じる宗教もある。', 'There are religions that believe in reincarnation.', '名詞', 133],
  ['因果',     'いんが',     'Karma; fate; cause and effect; retribution',
   'これも因果応報だろう。', 'This is probably the result of karma.', '名詞', 134],
  ['慈悲',     'じひ',       'Mercy; compassion; benevolence; charity',
   '慈悲の心を持って人に接する。', 'I deal with people with a compassionate heart.', '名詞', 135],

  // ── 名詞：経営・組織 (Management / Organization) ────────────────────────────
  ['刷新',     'さっしん',   'Reform; renovation; renewal; overhaul',
   '組織の刷新が求められた。', 'The renewal of the organization was demanded.', '名詞', 136],
  ['掌握',     'しょうあく', 'Grasping; seizing; taking hold of; command',
   '状況を完全に掌握した。', 'I completely grasped the situation.', '名詞', 137],
  ['統括',     'とうかつ',   'Control; supervision; coordination; overall management',
   '部門全体を統括する立場にある。', 'I am in a position to oversee the entire department.', '名詞', 138],
  ['折衝',     'せっしょう', 'Negotiation; bargaining; diplomatic dealings',
   '価格交渉の折衝を重ねた。', 'I repeated negotiations over pricing.', '名詞', 139],
  ['再興',     'さいこう',   'Revival; restoration; resurgence; renaissance',
   '伝統工芸の再興に努めた。', 'I worked toward the revival of traditional crafts.', '名詞', 140],

  // ── 動詞 (Verbs) ─────────────────────────────────────────────────────────────
  ['慮る',     'おもんぱかる','To give careful consideration; to take into account; to weigh',
   '相手の立場を慮って発言した。', 'I spoke while carefully considering the other person\'s position.', '動詞', 141],
  ['蠢く',     'うごめく',   'To wriggle; to squirm; to crawl; to move about',
   '虫が地面を蠢いている。', 'Insects are wriggling on the ground.', '動詞', 142],
  ['疎む',     'うとむ',     'To shun; to hold at a distance; to estrange',
   '周囲から疎まれる存在になった。', 'I became someone shunned by those around me.', '動詞', 143],
  ['諫める',   'いさめる',   'To remonstrate; to admonish; to counsel against',
   '部下の暴走を諫めた。', 'I remonstrated against my subordinate\'s recklessness.', '動詞', 144],
  ['弄ぶ',     'もてあそぶ', 'To toy with; to trifle with; to make sport of',
   '人の感情を弄ぶ行為は許せない。', 'Playing with people\'s emotions is unforgivable.', '動詞', 145],
  ['葬る',     'ほうむる',   'To bury; to inter; to dispose of; to consign to oblivion',
   '過去を葬り去ろうとした。', 'He tried to consign the past to oblivion.', '動詞', 146],
  ['貶める',   'おとしめる', 'To belittle; to disparage; to degrade; to demean',
   '他人を貶めるような言動は慎むべきだ。', 'One should refrain from words and actions that belittle others.', '動詞', 147],
  ['佇む',     'たたずむ',   'To stand still; to linger; to loiter in thought',
   '彼女は窓辺に佇んでいた。', 'She was standing quietly by the window.', '動詞', 148],
  ['蔑む',     'さげすむ',   'To despise; to scorn; to look down on; to hold in contempt',
   '弱い者を蔑む行為は卑劣だ。', 'Despising the weak is cowardly.', '動詞', 149],
  ['凌ぐ',     'しのぐ',     'To endure; to surpass; to shelter from; to hold out',
   '困難な時期を凌いだ。', 'We endured a difficult period.', '動詞', 150],
  ['欺く',     'あざむく',   'To deceive; to delude; to trick; to mislead',
   '人を欺く行為は許されない。', 'Deceiving people is not permitted.', '動詞', 151],
  ['阻む',     'はばむ',     'To obstruct; to hinder; to impede; to stand in the way of',
   '前進を阻む壁があった。', 'There was a wall obstructing our advance.', '動詞', 152],
  ['孕む',     'はらむ',     'To contain; to be pregnant with; to harbor; to involve',
   '危険を孕んだ計画だ。', 'It is a plan harboring danger.', '動詞', 153],
  ['疎んじる', 'うとんじる', 'To treat coldly; to hold in contempt; to alienate',
   '才能ゆえに疎んじられた。', 'He was alienated because of his talent.', '動詞', 154],
  ['贖う',     'あがなう',   'To atone for; to redeem; to compensate for',
   '罪を贖うために努力した。', 'I made efforts to atone for my sins.', '動詞', 155],
  ['傍聴する', 'ぼうちょうする','To attend and observe; to sit in on; to audit',
   '国会委員会を傍聴した。', 'I attended and observed the parliamentary committee.', '動詞', 156],
  ['踏襲する', 'とうしゅうする','To follow; to carry on; to inherit; to adhere to',
   '前任者の方針を踏襲した。', 'I followed the policies of my predecessor.', '動詞', 157],
  ['凌駕する', 'りょうがする','To surpass; to overtake; to exceed; to outstrip',
   '最新技術が従来技術を凌駕した。', 'The latest technology surpassed conventional technology.', '動詞', 158],
  ['翻弄する', 'ほんろうする','To toss about; to play with; to manipulate; to toy with',
   '運命に翻弄された人生だった。', 'It was a life tossed about by fate.', '動詞', 159],
  ['逸する',   'いっする',   'To miss; to let slip; to deviate; to lose',
   '好機を逸してしまった。', 'I let a good opportunity slip.', '動詞', 160],

  // ── 形容詞・形容動詞 (Adjectives) ───────────────────────────────────────────
  ['曖昧',     'あいまい',   'Vague; ambiguous; unclear; equivocal',
   '曖昧な表現は誤解を招く。', 'Vague expressions lead to misunderstanding.', '形容動詞', 161],
  ['恣意的',   'しいてき',   'Arbitrary; capricious; based on whim',
   '恣意的な人事は組織を乱す。', 'Arbitrary personnel decisions disturb the organization.', '形容動詞', 162],
  ['形而上',   'けいじじょう','Metaphysical; abstract; immaterial',
   '形而上の問題に答えはない。', 'There are no answers to metaphysical questions.', '形容動詞', 163],
  ['荘厳',     'そうごん',   'Solemn; majestic; grand; sublime',
   '荘厳な雰囲気の教会だ。', 'It is a church with a solemn atmosphere.', '形容動詞', 164],
  ['苛烈',     'かれつ',     'Severe; harsh; intense; fierce',
   '苛烈な競争が続いている。', 'Fierce competition continues.', '形容動詞', 165],
  ['難解',     'なんかい',   'Difficult; abstruse; hard to understand; recondite',
   '難解な文章を読み解いた。', 'I deciphered the difficult text.', '形容動詞', 166],
  ['唐突',     'とうとつ',   'Abrupt; sudden; unexpected; out of the blue',
   '唐突な質問に戸惑った。', 'I was flustered by the abrupt question.', '形容動詞', 167],
  ['肝要',     'かんよう',   'Vital; essential; of utmost importance; critical',
   '信頼関係の構築が肝要だ。', 'Building a relationship of trust is essential.', '形容動詞', 168],
  ['精緻',     'せいち',     'Elaborate; meticulous; exquisite; intricate',
   '精緻な細工が施された工芸品だ。', 'It is a craft item with elaborate workmanship.', '形容動詞', 169],
  ['稀薄',     'きはく',     'Thin; sparse; diluted; lacking in substance',
   '空気が稀薄な高山地帯だ。', 'It is a high mountain area with thin air.', '形容動詞', 170],
  ['厳粛',     'げんしゅく', 'Grave; solemn; serious; austere',
   '厳粛な式典が執り行われた。', 'A solemn ceremony was conducted.', '形容動詞', 171],
  ['陳腐',     'ちんぷ',     'Hackneyed; clichéd; trite; stale; commonplace',
   '陳腐な発想から脱却すべきだ。', 'We should break free from hackneyed ideas.', '形容動詞', 172],
  ['軽率',     'けいそつ',   'Rash; careless; thoughtless; hasty; imprudent',
   '軽率な発言が誤解を生んだ。', 'A careless remark created a misunderstanding.', '形容動詞', 173],
  ['旺盛',     'おうせい',   'Vigorous; active; thriving; strong; enthusiastic',
   '探究心が旺盛な子どもだ。', 'It is a child with a vigorous spirit of inquiry.', '形容動詞', 174],
  ['実直',     'じっちょく', 'Honest; upright; straightforward; sincere',
   '実直な人柄が信頼を集めた。', 'His honest character earned trust.', '形容動詞', 175],
  ['冗長',     'じょうちょう','Verbose; redundant; prolix; long-winded; wordy',
   '冗長な説明を省略した。', 'I omitted the verbose explanation.', '形容動詞', 176],
  ['迂遠',     'うえん',     'Roundabout; circuitous; indirect; overly elaborate',
   '迂遠な方法を避けた。', 'I avoided roundabout methods.', '形容動詞', 177],
  ['端的',     'たんてき',   'Frank; direct; to the point; concise; plainly',
   '端的に結論を述べた。', 'I stated the conclusion directly.', '形容動詞', 178],
  ['漠然',     'ばくぜん',   'Vague; obscure; dim; hazy; nebulous',
   '漠然とした不安を感じた。', 'I felt a vague sense of unease.', '形容動詞', 179],
  ['俗悪',     'ぞくあく',   'Vulgar; in poor taste; boorish; base',
   '俗悪な表現は避けるべきだ。', 'Vulgar expressions should be avoided.', '形容動詞', 180],

  // ── 名詞：対人関係 (Interpersonal Relations) ────────────────────────────────
  ['蔑視',     'べっし',     'Contempt; scorn; disdain; looking down on',
   '女性への蔑視的な発言が問題視された。', 'Contemptuous remarks toward women were viewed as a problem.', '名詞', 181],
  ['宥和',     'ゆうわ',     'Appeasement; conciliation; pacification',
   '宥和政策の危うさを指摘した。', 'I pointed out the danger of an appeasement policy.', '名詞', 182],
  ['懐柔',     'かいじゅう', 'Winning over; conciliation; bringing around; mollification',
   '反対派を懐柔しようとした。', 'He tried to win over the opposition.', '名詞', 183],
  ['疎外',     'そがい',     'Alienation; estrangement; exclusion; ostracism',
   '社会からの疎外感を覚えた。', 'I felt a sense of alienation from society.', '名詞', 184],
  ['慈愛',     'じあい',     'Affection; love; benevolence; tender care',
   '慈愛に満ちた眼差しで見守った。', 'She watched over with eyes full of affection.', '名詞', 185],

  // ── 名詞：言語・表現 (Language / Expression) ────────────────────────────────
  ['言及',     'げんきゅう', 'Reference; mention; allusion; touching upon',
   '過去の失敗に言及した。', 'I made reference to past failures.', '名詞', 186],
  ['敷衍',     'ふえん',     'Elaboration; amplification; paraphrase; expansion',
   '概念を敷衍して説明した。', 'I explained by elaborating on the concept.', '名詞', 187],
  ['含意',     'がんい',     'Implication; connotation; implied meaning',
   '発言の含意を読み取った。', 'I read the implied meaning of the statement.', '名詞', 188],

  // ── 名詞：その他 (Miscellaneous) ────────────────────────────────────────────
  ['先鋭',     'せんえい',   'Sharpness; keenness; radicalism; avant-garde',
   '先鋭な議論が交わされた。', 'Sharp arguments were exchanged.', '名詞', 189],
  ['鋭敏',     'えいびん',   'Sharp; keen; acute; sensitive; astute',
   '鋭敏な感覚を持つ芸術家だ。', 'He is an artist with keen senses.', '名詞', 190],
  ['旧弊',     'きゅうへい', 'Old abuses; obsolete customs; outmoded ways',
   '旧弊を打破して改革を進めた。', 'We broke old abuses and advanced reform.', '名詞', 191],
  ['悪弊',     'あくへい',   'Evil practice; bad habit; vice; corrupt custom',
   '組織内の悪弊を根絶した。', 'We eradicated evil practices within the organization.', '名詞', 192],
  ['不毛',     'ふもう',     'Barren; unfruitful; sterile; futile; unproductive',
   '不毛な議論を繰り返した。', 'We repeatedly engaged in futile arguments.', '名詞', 193],
  ['空疎',     'くうそ',     'Empty; hollow; vacant; meaningless; insubstantial',
   '空疎な言葉が並ぶ演説だった。', 'It was a speech filled with hollow words.', '名詞', 194],
  ['矛盾',     'むじゅん',   'Contradiction; inconsistency; paradox; conflict',
   '主張に矛盾が含まれている。', 'The argument contains a contradiction.', '名詞', 195],
  ['相克',     'そうこく',   'Conflict; mutual opposition; contending forces',
   '自由と平等の相克は歴史的問題だ。', 'The conflict between freedom and equality is a historical issue.', '名詞', 196],
  ['捏造',     'ねつぞう',   'Fabrication; falsification; making up; concoction',
   'データ捏造が発覚して問題になった。', 'Data fabrication was discovered and became an issue.', '名詞', 197],
  ['陶冶',     'とうや',     'Cultivation; training; shaping of character; molding',
   '人格の陶冶を目指す教育だ。', 'It is an education aimed at the cultivation of character.', '名詞', 198],
  ['開拓',     'かいたく',   'Pioneering; development; reclamation; opening up',
   '新市場の開拓に乗り出した。', 'We set out to develop new markets.', '名詞', 199],
  ['権化',     'ごんげ',     'Incarnation; embodiment; avatar; personification',
   '悪の権化と呼ばれた人物だ。', 'He was called the embodiment of evil.', '名詞', 200],

  // ── 続き (continued) ─────────────────────────────────────────────────────────
  ['矜恃',     'きょうじ',   'Pride; self-respect; dignity (alternate form of 矜持)',
   '武士としての矜恃を失わなかった。', 'He never lost his dignity as a samurai.', '名詞', 201],
  ['払底',     'ふってい',   'Complete exhaustion; running out; depletion of stock',
   '物資が払底した。', 'Supplies were completely exhausted.', '名詞', 202],
  ['撞着',     'どうちゃく', 'Contradiction; inconsistency; clash',
   '自家撞着に陥った議論だ。', 'It is an argument that has fallen into self-contradiction.', '名詞', 203],
  ['一辺倒',   'いっぺんとう','One-sidedness; leaning entirely to one side',
   '欧米一辺倒の外交政策を見直した。', 'We reviewed the one-sided foreign policy favoring the West.', '名詞', 204],
  ['拘泥',     'こうでい',   'Being too particular; sticking to; being over-scrupulous',
   '細部に拘泥して全体を見失った。', 'He was too particular about details and lost sight of the whole.', '名詞', 205],
  ['忖度',     'そんたく',   'Inferring another\'s feelings; reading the air; second-guessing',
   '忖度による意思決定が問題だ。', 'Decision-making based on second-guessing others is a problem.', '名詞', 206],
  ['齟齬',     'そご',       'Discrepancy; mismatch; going against each other',
   '認識の齟齬を解消した。', 'We resolved the discrepancy in understanding.', '名詞', 207],
  ['諦観',     'ていかん',   'Resignation; acceptance; philosophical detachment; clear vision',
   '人生の無常を諦観を持って受け入れた。', 'I accepted the impermanence of life with philosophical detachment.', '名詞', 208],
  ['冗漫',     'じょうまん', 'Prolix; verbose; diffuse; rambling; tediously long',
   '冗漫な文章を簡潔にまとめた。', 'I condensed the verbose text into something concise.', '名詞', 209],
  ['逸材',     'いつざい',   'Outstanding talent; exceptional person; rare ability',
   '彼は時代の逸材だと評された。', 'He was praised as an outstanding talent of the era.', '名詞', 210],
  ['逸脱',     'いつだつ',   'Deviation; departure; transgression; digression',
   '本題から逸脱した議論が続いた。', 'A discussion deviating from the main topic continued.', '名詞', 211],
  ['抑制',     'よくせい',   'Suppression; control; restraint; inhibition',
   '感情を抑制して冷静に対処した。', 'I suppressed my emotions and dealt with the situation calmly.', '名詞', 212],
  ['弛緩',     'しかん',     'Relaxation; laxity; loosening; flaccidity',
   '規律の弛緩が問題になった。', 'The laxity of discipline became a problem.', '名詞', 213],
  ['先入観',   'せんにゅうかん','Preconception; prejudice; preconceived notion',
   '先入観なく物事を見ることが大切だ。', 'It is important to look at things without preconceptions.', '名詞', 214],
  ['既成概念', 'きせいがいねん','Established concept; conventional idea; preconceived notion',
   '既成概念にとらわれない発想が必要だ。', 'Ideas not constrained by established concepts are necessary.', '名詞', 215],
  ['慣例',     'かんれい',   'Custom; convention; precedent; established practice',
   '慣例を破った決断だった。', 'It was a decision that broke with convention.', '名詞', 216],
  ['通念',     'つうねん',   'Commonly accepted idea; prevailing notion; general understanding',
   '通念を覆す発見だった。', 'It was a discovery that overturned the commonly accepted idea.', '名詞', 217],
  ['所産',     'しょさん',   'Product; result; outcome; creation; fruit of one\'s work',
   'この成果は長年の努力の所産だ。', 'This achievement is the product of years of effort.', '名詞', 218],
  ['精華',     'せいか',     'Cream; best part; essence; quintessence; flower',
   '文化の精華が集まった展覧会だ。', 'It is an exhibition where the best of culture has gathered.', '名詞', 219],
  ['醸成',     'じょうせい', 'Fostering; breeding; cultivation; forming (of an atmosphere)',
   '信頼関係の醸成に努めた。', 'I worked to foster a relationship of trust.', '名詞', 220],

  // ── さらに続き (more) ─────────────────────────────────────────────────────────
  ['蓋然性',   'がいぜんせい','Probability; likelihood; plausibility',
   '蓋然性が高い仮説を採用した。', 'I adopted the hypothesis with the highest probability.', '名詞', 221],
  ['恣意',     'しい',       'Arbitrariness; selfishness; acting on one\'s own will',
   '恣意に基づく判断は信頼を損なう。', 'Judgments based on arbitrariness undermine trust.', '名詞', 222],
  ['傍証',     'ぼうしょう', 'Circumstantial evidence; corroborating evidence',
   '傍証を積み重ねて立証した。', 'I proved it by accumulating circumstantial evidence.', '名詞', 223],
  ['直截',     'ちょくせつ', 'Direct; straightforward; frank; without beating around the bush',
   '直截な物言いを好む人だ。', 'He is a person who prefers frank speech.', '名詞', 224],
  ['牽引',     'けんいん',   'Traction; pulling; leading; driving force',
   '経済を牽引する産業が変わった。', 'The industry driving the economy has changed.', '名詞', 225],
  ['趨勢',     'すうせい',   'Trend; tendency; drift; general direction',
   '時代の趨勢に乗り遅れた。', 'I fell behind the trend of the times.', '名詞', 226],
  ['潮流',     'ちょうりゅう','Current; trend; mainstream; tide',
   '国際的な潮流に合わせた政策だ。', 'It is a policy in line with international trends.', '名詞', 227],
  ['変革',     'へんかく',   'Reform; change; transformation; revolution',
   '社会変革を目指す運動だ。', 'It is a movement aimed at social transformation.', '名詞', 228],
  ['革新',     'かくしん',   'Innovation; reform; renewal; breakthrough',
   '技術革新が産業を変えた。', 'Technological innovation changed industry.', '名詞', 229],
  ['保守',     'ほしゅ',     'Conservatism; maintenance; keeping intact',
   '保守と革新の対立が続く。', 'The confrontation between conservatism and innovation continues.', '名詞', 230],
];

// ─── GRAMMAR ──────────────────────────────────────────────────────────────────
// Sourced from Shin Kanzen Master N1 文法, So-Matome N1, and JLPT N1 grammar lists.
// formality_level: 書き言葉 = written/formal | 話し言葉 = spoken | 中立 = neutral
// ──────────────────────────────────────────────────────────────────────────────

export const grammar: GrammarSeed[] = [
  ['〜に際して／に際し',
   'On the occasion of; at the time of; when (something important happens)',
   'Verb (dict/ます-stem) ＋ に際して　／　Noun ＋ に際して',
   '渡航に際して、海外保険に加入した。',
   'When traveling abroad, I took out overseas insurance.',
   'Used for important, often one-time events. Cannot be used for routine matters. More formal than 〜とき.',
   '書き言葉'],

  ['〜をもって',
   'With; by means of; using; as of (time); at the end of',
   'Noun ＋ をもって（して）',
   'これをもって、本日の会議を終了いたします。',
   'With this, we conclude today\'s meeting.',
   'Has two main uses: (1) means/method (＝によって) for formal contexts; (2) indicates a cut-off time (「本日をもって閉店」). Very formal.',
   '書き言葉'],

  ['〜ならでは（の）',
   'Unique to; only possible with; characteristic of; something that can only come from',
   'Noun ＋ ならでは（の＋Noun）',
   'これはプロならではの技術だ。',
   'This is a technique only possible from a professional.',
   'Expresses that X is distinctive to / only found in the preceding noun. Always a positive characteristic.',
   '中立'],

  ['〜とあって',
   'Because (of a special or unusual circumstance); given that; since',
   'Noun / Phrase ＋ とあって',
   '三連休とあって、観光地は混雑している。',
   'Because it is a three-day holiday, tourist spots are crowded.',
   'The preceding clause is a special or notable situation. It explains why the result in the main clause happens. Written/journalistic style.',
   '書き言葉'],

  ['〜とあれば',
   'If it is the case that; if it means; if it involves',
   'Noun / Plain form ＋ とあれば',
   '国のためとあれば、命も惜しくない。',
   'If it is for the country, I do not even mind sacrificing my life.',
   'Expresses willingness to do something under a special condition. The condition is presented as a compelling reason.',
   '書き言葉'],

  ['〜べく',
   'In order to; for the purpose of; aiming to (formal intention)',
   'Verb (dict form) ＋ べく　※する→すべく',
   '優勝を目指すべく、猛練習を続けた。',
   'In order to aim for the championship, I continued intense practice.',
   'Classical/literary equivalent of 〜ために. する becomes すべく. Used in formal writing and set expressions.',
   '書き言葉'],

  ['〜とばかりに',
   'As if to say; acting as though (with that attitude/expression); virtually saying',
   'Quotation ＋ とばかりに　／　Plain form ＋ とばかりに',
   '「邪魔をするな」とばかりに、彼は無視した。',
   'As if to say "Don\'t bother me," he ignored us.',
   'Describes someone\'s attitude or behavior that clearly communicates something without words. The quote is often implicit.',
   '中立'],

  ['〜んばかりに／んばかりの',
   'As if about to; on the verge of; looking as though',
   'Verb (ない-form stem) ＋ んばかりに　※する→せんばかり',
   '泣かんばかりの顔で訴えた。',
   'He appealed with a face that looked as though he were about to cry.',
   'Expresses an extreme state almost reaching the described action. Classical negative stem + ん (archaic negative). する→せんばかり.',
   '書き言葉'],

  ['〜を皮切りに／を皮切りとして',
   'Starting with; beginning with; using X as the starting point',
   'Noun ＋ を皮切りに（して）／を皮切りとして',
   '東京公演を皮切りに、全国ツアーが始まった。',
   'Starting with the Tokyo performance, the nationwide tour began.',
   '皮切り originally means the first incision in surgery. Now used to indicate the first in a series of events.',
   '書き言葉'],

  ['〜をよそに',
   'Indifferent to; ignoring; unconcerned with; regardless of (others\' feelings)',
   'Noun ＋ をよそに',
   '周囲の心配をよそに、彼は危険な登山を続けた。',
   'Indifferent to the concerns of those around him, he continued the dangerous climb.',
   'Implies the subject acts without regard for someone else\'s feelings, concerns, or the situation. Often has a slightly negative connotation.',
   '書き言葉'],

  ['〜をものともせず（に）',
   'Undaunted by; in defiance of; not letting X stop one',
   'Noun ＋ をものともせず（に）',
   '激しい風雨をものともせず、彼は前進した。',
   'Undaunted by the fierce wind and rain, he pressed forward.',
   'Expresses overcoming or ignoring a major obstacle with great determination or courage. Positive connotation.',
   '書き言葉'],

  ['〜もさることながら',
   'Not only X, but also (Y is even more so); X goes without saying, but (Y as well)',
   'Noun ＋ もさることながら',
   '費用もさることながら、時間もかかる作業だ。',
   'Not only does it cost money, but it is also a time-consuming task.',
   'Acknowledges X as true/important and adds that Y is at least as noteworthy. The nuance is that Y may be even more significant than X.',
   '書き言葉'],

  ['〜にもまして',
   'More than ever; even more than; above all; surpassing',
   'Noun / これ・何 ＋ にもまして',
   '今年は例年にもまして暑い夏だ。',
   'This year is an even hotter summer than usual.',
   'Expresses that the current state exceeds or surpasses the standard comparison. Common phrases: 何にもまして, 以前にもまして.',
   '書き言葉'],

  ['〜といえども',
   'Even though; even if; although; no matter how much (concession)',
   'Noun / Plain form ＋ といえども',
   '専門家といえども、間違えることがある。',
   'Even experts can make mistakes.',
   'Classical concessive form. More formal than 〜でも or 〜けれども. Used in formal argument, essays, and set expressions.',
   '書き言葉'],

  ['〜ともなると／ともなれば',
   'When it comes to; now that one has become; if it is a matter of',
   'Noun ＋ ともなると／ともなれば',
   '部長ともなると、責任も大きくなる。',
   'When it comes to being a department head, responsibility also becomes great.',
   'Expresses that with a certain status, role, or situation, certain things naturally follow. Implies elevated position or significant circumstance.',
   '中立'],

  ['〜ながらに（して）／ながらの',
   'While being; remaining in that state; as it is; from birth',
   'Noun / Verb (ます-stem) ＋ ながらに（して）',
   '彼は生まれながらにして才能を持っていた。',
   'He had talent from birth.',
   'Expresses that a state continues as it is, or that something has been true since a particular origin point. 生まれながらに is a fixed phrase.',
   '書き言葉'],

  ['〜そばから',
   'As soon as; no sooner than; just as fast as (repeated frustrating action)',
   'Verb (plain past / dict) ＋ そばから',
   '片付けるそばから、子供が散らかす。',
   'As fast as I tidy up, the children make a mess.',
   'Expresses frustration that one action is immediately undone by another repeated action. Carries a nuance of futility or exasperation.',
   '話し言葉'],

  ['〜ではあるまいし',
   'It\'s not as if; it\'s not like you\'re (a); since you\'re not',
   'Noun / Plain form ＋ ではあるまいし',
   '子供ではあるまいし、そんなことで泣かないでください。',
   'It\'s not as if you\'re a child, so please don\'t cry over something like that.',
   'Used to rebuke or advise someone by pointing out that the current behavior is inappropriate for their status. あるまい = ないだろう.',
   '話し言葉'],

  ['〜とはいえ',
   'Even so; that said; although; granted that; admittedly',
   'Plain form / Noun ＋ とはいえ',
   '冬とはいえ、今日は暖かい。',
   'Even though it is winter, today is warm.',
   'Acknowledges the preceding clause as true but introduces a contrasting or qualifying statement. Similar to 〜けれども but more formal.',
   '中立'],

  ['〜にひきかえ',
   'In contrast to; as opposed to; unlike; in sharp contrast with',
   'Noun / Plain form ＋ にひきかえ',
   '兄にひきかえ、弟は勤勉だ。',
   'In contrast to his older brother, the younger brother is diligent.',
   'Draws a clear contrast between two things, often of the same category. The contrast is usually stark or surprising.',
   '書き言葉'],

  ['〜はいざしらず／はともかく（として）',
   'I don\'t know about X, but; leaving aside X; X may be one thing, but',
   'Noun ＋ はいざしらず　／　Noun ＋ はともかく（として）',
   '昔はいざしらず、今は事情が違う。',
   'I don\'t know about the past, but things are different now.',
   'The speaker acknowledges that X might be understandable in some context but emphasizes that Y (the main point) is different or more important.',
   '中立'],

  ['〜いかんによらず／いかんにかかわらず',
   'Regardless of; irrespective of; no matter what',
   'Noun ＋ のいかんによらず／のいかんにかかわらず',
   '理由のいかんによらず、遅刻は許されない。',
   'Regardless of the reason, tardiness is not permitted.',
   'Formal expression. いかん means "how" or "what kind of." Can also appear as 〜いかんを問わず (irrespective of).',
   '書き言葉'],

  ['〜に足る（足りる）',
   'Worth doing; deserving of; sufficient for; worthy of',
   'Verb (dict form) / Noun ＋ に足る（足りる）',
   '彼は信頼に足る人物だ。',
   'He is a person worthy of trust.',
   'Formal, written expression. Negative form 〜に足りない/足らない means "not worth" or "insufficient." 取るに足りない is a set phrase (trivial/negligible).',
   '書き言葉'],

  ['〜をおいて（〜ない）',
   'Other than; except for; there is no one/nothing but; apart from',
   'Noun ＋ をおいて（〜はいない/ない）',
   'この仕事を任せられるのは、彼をおいて他にいない。',
   'There is no one but him who can be entrusted with this job.',
   'Emphasizes uniqueness or irreplaceability. Almost always appears with a negative main clause.',
   '書き言葉'],

  ['〜に即して／に即した',
   'In accordance with; based on; in line with; following closely',
   'Noun ＋ に即して／に即した＋Noun',
   '現実に即した対策を立てた。',
   'We formulated measures in accordance with reality.',
   '即する means to conform to / be appropriate to. Implies close adherence to actual conditions, facts, or standards.',
   '書き言葉'],

  ['〜なしには／なくしては',
   'Without; it cannot be done without; if it weren\'t for',
   'Noun ＋ なしには／なくしては　（＋negative result）',
   '努力なしには、成功は得られない。',
   'Without effort, success cannot be obtained.',
   'Emphasizes the absolute necessity of the preceding noun. The main clause almost always contains a negative or negative-meaning expression.',
   '書き言葉'],

  ['〜にとどまらず',
   'Not limited to; not just; extending beyond; going further than',
   'Noun ＋ にとどまらず',
   '影響は国内にとどまらず、海外にも及んだ。',
   'The impact was not limited to the domestic arena but extended overseas as well.',
   'Expresses that something goes beyond an expected or stated boundary. Written/formal style.',
   '書き言葉'],

  ['〜を限りに',
   'As the last; ending with; as of (a final moment); from X on',
   'Noun（time/event）＋ を限りに',
   '本日を限りに、この職を辞します。',
   'As of today, I will resign from this position.',
   'Marks a boundary point after which something stops. Often used in formal announcements. 声を限りに is a fixed expression meaning "at the top of one\'s voice."',
   '書き言葉'],

  ['〜を踏まえて',
   'Based on; taking into account; in light of; building on',
   'Noun ＋ を踏まえて（，〜する）',
   '前回の失敗を踏まえて、改善策を講じた。',
   'Based on the previous failure, we took corrective measures.',
   '踏まえる means to stand on/base oneself on. Implies using prior knowledge, data, or experience as a foundation for action.',
   '中立'],

  ['〜をめぐって',
   'Concerning; surrounding; over the issue of; with regard to (controversy)',
   'Noun ＋ をめぐって／をめぐる＋Noun',
   '原発の再稼働をめぐって議論が続いている。',
   'Discussion continues surrounding the restart of nuclear power plants.',
   'Used when something is the center of discussion, conflict, or debate. Often implies controversy or dispute.',
   '中立'],

  ['〜にあたって／にあたり',
   'At the time of; when doing; on the occasion of; in undertaking',
   'Verb (dict form) / Noun ＋ にあたって／にあたり',
   '新事業を開始するにあたり、市場調査を行った。',
   'When starting the new business, we conducted market research.',
   'Similar to に際して. Used for important actions or events. にあたり is more formal than にあたって.',
   '書き言葉'],

  ['〜のもとで／もとに',
   'Under; based on; in accordance with; under the condition of',
   'Noun ＋ のもとで／もとに',
   '厳しい条件のもとで訓練を続けた。',
   'I continued training under strict conditions.',
   'Two main uses: (1) under someone\'s guidance/supervision (先生のもとで学ぶ); (2) under a condition or rule (この法律のもとで).',
   '中立'],

  ['〜からして',
   'Judging from; even; for a start; from the very beginning of',
   'Noun ＋ からして',
   'タイトルからして、難しそうな本だ。',
   'Judging from the title alone, it looks like a difficult book.',
   'Two uses: (1) judging from a representative example (からして/からすると); (2) even the most basic aspect (名前からして変だ). Slightly critical nuance possible.',
   '中立'],

  ['〜からといって',
   'Just because; even though; the fact that X doesn\'t mean Y',
   'Plain form ＋ からといって',
   '忙しいからといって、健康を無視していい理由にはならない。',
   'Just because you are busy does not mean it is acceptable to ignore your health.',
   'Challenges the validity of using X as a reason for Y. The main clause often contains a negative or critical statement.',
   '中立'],

  ['〜ずにはすまない',
   'Cannot avoid; will not do without; is compelled to; must',
   'Verb（ない-form stem）＋ ずにはすまない　※する→せずにはすまない',
   '間違いを犯したからには、謝罪せずにはすまない。',
   'Having made a mistake, one cannot avoid apologizing.',
   'Expresses social obligation or inevitability — not just personal feeling but what society/circumstances demand. する→せずにはすまない.',
   '中立'],

  ['〜ないではすまない',
   'Must; cannot get away without doing; is socially expected to',
   'Verb（ない-form）＋ ではすまない',
   'こんな失礼をしたのだから、謝らないではすまない。',
   'Having been so rude, I cannot get away without apologizing.',
   'Similar to 〜ずにはすまない but slightly more colloquial. Both express social necessity/compulsion.',
   '中立'],

  ['〜てやまない',
   'Never cease to; always; continues to (feel/hope/love)',
   'Verb（て-form）＋ やまない',
   '彼の回復を願ってやまない。',
   'I never cease to hope for his recovery.',
   'Expresses an emotion or state that never stops. Usually used with verbs of emotion: 願う、愛する、信じる、敬う.',
   '書き言葉'],

  ['〜をもってすれば',
   'If (one uses X); with the power/ability of; given X',
   'Noun ＋ をもってすれば',
   '彼の技術をもってすれば、解決できるはずだ。',
   'With his skill, it should be possible to solve it.',
   'Expresses that using a particular ability, resource, or means makes something possible. Often has an admiring or hypothetical nuance.',
   '書き言葉'],

  ['〜ことなしに',
   'Without doing; it cannot be done without',
   'Verb（dict form）＋ ことなしに（は）',
   '努力することなしに、成功は望めない。',
   'Without making effort, one cannot hope for success.',
   'Formal equivalent of 〜ずに in certain constructions. More emphatic and written.',
   '書き言葉'],

  ['〜たりとも〜ない',
   'Not even one; not a single; even one cannot be (wasted)',
   'Counter ＋ たりとも ＋ negative',
   '一瞬たりとも気を抜けない状況だった。',
   'It was a situation where I could not let my guard down for even an instant.',
   'Used with counters (一秒、一円、一人) to emphasize that even the smallest unit is included in the negative scope. Formal/emphatic.',
   '書き言葉'],

  ['〜べくして〜た',
   'As was bound to happen; inevitably; as expected to',
   'Verb（dict form）＋ べくして ＋ same verb（past）',
   '起こるべくして起こった災害だ。',
   'It is a disaster that was bound to happen.',
   'Expresses that the outcome was inevitable, often implying that it was foreseeable or predictable. The same verb appears twice.',
   '書き言葉'],

  ['〜に相違ない',
   'There is no doubt that; must be; certainly; without question',
   'Plain form / Noun ＋ に相違ない',
   '彼が犯人に相違ない。',
   'There is no doubt that he is the culprit.',
   'Formal, written equivalent of 〜に違いない. Used in formal writing, legal contexts, and classical-style expression.',
   '書き言葉'],

  ['〜ならいざしらず',
   'If it were X that would be one thing, but (since it\'s not)',
   'Noun / Plain form ＋ ならいざしらず',
   '学生ならいざしらず、社会人がそんな言い訳は通らない。',
   'If it were a student that would be one thing, but such an excuse doesn\'t work for a working adult.',
   'Expresses that while X might be acceptable, the actual situation (the main clause) is different. Implies the main situation is less forgivable or more serious.',
   '書き言葉'],

  ['〜のみならず',
   'Not only; not just; not merely (formal)',
   'Plain form / Noun ＋ のみならず',
   '健康のみならず、精神面でも大切なことだ。',
   'It is important not only for physical health but also for mental well-being.',
   'Formal written equivalent of 〜だけでなく. Used in essays, speeches, and formal documents.',
   '書き言葉'],

  ['〜まじき',
   'Should not; unworthy of; not befitting; unbefitting one\'s position',
   'Verb（dict form）＋ まじき ＋ Noun',
   '教師にあるまじき行為だ。',
   'It is conduct unworthy of a teacher.',
   'Classical negative auxiliary まじ + き (attributive form). In modern usage, nearly always as 〜にあるまじき or 〜としてあるまじき. Very formal/written.',
   '書き言葉'],

  ['〜かたがた',
   'While also; for the dual purpose of; combining X with Y',
   'Noun（verbal noun）＋ かたがた',
   'お礼かたがた、近況をご報告します。',
   'I am reporting my recent situation, while also expressing my gratitude.',
   'Indicates doing one main thing while simultaneously accomplishing another, usually a social courtesy. 限られた名詞 (お礼、お詫び、ご挨拶). Written/formal.',
   '書き言葉'],

  ['〜かたわら',
   'While; alongside; in addition to; on the side',
   'Verb（dict form / ている）/ Noun ＋ かたわら',
   '会社に勤めるかたわら、小説を書いている。',
   'I write novels while working at a company.',
   'Describes a secondary or side activity done alongside a main one, often expressing a continuous dual role. Written/formal.',
   '書き言葉'],

  ['〜がてら',
   'While; on the way; taking the opportunity to; combining with',
   'Verb（ます-stem）/ Noun ＋ がてら',
   '散歩がてら、スーパーに寄った。',
   'I stopped by the supermarket on my walk.',
   'Indicates doing a secondary action incidentally while doing the main one. The main action serves as a vehicle for the secondary. More casual than かたがた.',
   '中立'],

  ['〜ついでに',
   'While one is at it; on the occasion of; while you\'re at it',
   'Verb（dict / た form）/ Noun ＋ のついでに',
   '買い物のついでに、図書館に寄った。',
   'I stopped by the library while I was out shopping.',
   'The secondary action piggybacks on the primary. The primary is the main purpose; the secondary is opportunistic. More casual.',
   '話し言葉'],

  ['〜ともあろう（者が）',
   'For someone of X\'s standing; being no less than; a person as important as',
   'Noun ＋ ともあろう（者が/人が）',
   '総理大臣ともあろう方がそんな失言をするとは。',
   'To think that someone of the Prime Minister\'s standing would make such a gaffe.',
   'Expresses surprise or criticism that a person of high status behaved in an unbecoming way. Usually followed by a surprising negative outcome.',
   '書き言葉'],

  ['〜ずして／ずに',
   'Without doing; not having done; without resorting to (formal/literary)',
   'Verb（ない-stem）＋ ずして／ずに　※する→せずして',
   '努力せずして成功を望むのは甘い。',
   'It is naive to hope for success without making effort.',
   'Classical negative form. ずして is more literary/formal than ずに. する→せずして. Used in proverbs, formal speeches, essays.',
   '書き言葉'],

  ['〜をして〜させる',
   'To make/cause/have someone do something (literary causative)',
   'Noun（person）＋ をして ＋ Verb（させる）',
   '彼の演技は観客をして涙を流させた。',
   'His performance moved the audience to tears.',
   'Classical causative construction. Noun をして indicates the agent. Much more literary and archaic than 〜に〜させる. Found in formal essays and literature.',
   '書き言葉'],

  ['〜ともすれば／ともすると',
   'Apt to; liable to; prone to; there is a tendency to',
   'Verb（plain）＋ ともすれば／ともすると',
   '忙しいと、ともすれば健康を後回しにしがちだ。',
   'When busy, one is apt to put health on the back burner.',
   'Describes a tendency or inclination, often an undesirable one. Implies that without care, this outcome easily occurs.',
   '中立'],

  ['〜にして',
   '(1) At the age/point of; (2) being X and also Y; (3) even for X',
   'Noun ＋ にして',
   '彼は30歳にして大企業の社長となった。',
   'He became the president of a major company at the age of 30.',
   'Multiple uses: (1) age/time milestone (30歳にして); (2) simultaneous quality (厳にして慈); (3) even for X (専門家にして難しい). Context-dependent.',
   '書き言葉'],

  ['〜いかんでは',
   'Depending on; according to; depending on the nature of',
   'Noun（の）＋ いかんでは',
   '結果のいかんでは、辞任も考えている。',
   'Depending on the results, I am also considering resignation.',
   'Expresses that the outcome of the main clause depends on the content of the preceding noun. いかん = どのようであるか.',
   '書き言葉'],

  ['〜をかこつける／にかこつけて',
   'Using as a pretext; under the guise of; using X as an excuse',
   'Noun ＋ にかこつけて',
   '出張にかこつけて、観光を楽しんだ。',
   'Using the business trip as a pretext, I enjoyed sightseeing.',
   'Implies using something as a convenient excuse or cover story for doing something else, often something one wants to do personally.',
   '中立'],

  ['〜なくして（は）',
   'Without; it is impossible without; if not for',
   'Noun ＋ なくして（は）／なくしては',
   '根気なくしては、この仕事は続けられない。',
   'Without patience, this work cannot be continued.',
   'Emphasizes that the preceding noun is indispensable. The main clause usually expresses impossibility or negative outcome. Formal.',
   '書き言葉'],
];

// ─── READING PASSAGES ─────────────────────────────────────────────────────────
export type PassageSeed = {
  title: string;
  content: string;
  category: string;
  questions: QuestionSeed[];
};

export type QuestionSeed = {
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
};

export const passages: PassageSeed[] = [
  {
    title: '人工知能と創造性',
    category: 'テクノロジー',
    content: `近年、人工知能（AI）の発展は目覚ましく、その応用範囲は従来の計算処理やデータ分析を超え、音楽、絵画、文学といった創造的領域にまで及んでいる。しかし、AIが生み出す「作品」は本当に創造的と言えるのだろうか。

創造性とは何かを定義することは難しい。一般的には、既存の概念を新しい方法で組み合わせ、独創的な何かを生み出す能力とされる。この観点から見れば、大量のデータから学習し、パターンを認識して新しいコンテンツを生成するAIは、確かに創造的活動を行っていると見ることもできる。

しかし、多くの哲学者や芸術家は異議を唱える。彼らによれば、真の創造性には意図、感情、そして自己意識が不可欠である。人間の芸術家は自らの経験、苦悩、喜びを作品に込める。その作品には作者の魂が宿っている。AIにはそのような内的世界が存在せず、ただデータを処理しているに過ぎないという見方だ。

この議論は単なる哲学的問いにとどまらず、著作権、芸術家の雇用、そして人間の存在意義にまで影響を及ぼす重要な問題である。`,
    questions: [
      {
        question: '本文によれば、AIの創造性に対する否定的な意見の根拠は何か？',
        option_a: 'AIは計算能力が人間より劣るから',
        option_b: 'AIには感情や自己意識がないから',
        option_c: 'AIは学習データが不十分だから',
        option_d: 'AIは著作権を持てないから',
        correct_answer: 'B',
        explanation: '第三段落で「真の創造性には意図、感情、そして自己意識が不可欠」とあり、AIにはそれらがないという主張が述べられている。',
      },
      {
        question: '筆者がこの問題を「単なる哲学的問いにとどまらない」と述べた理由として最も適切なものはどれか？',
        option_a: '哲学は非実用的な学問だから',
        option_b: '著作権や雇用など社会的影響があるから',
        option_c: 'AIの技術が急速に進化しているから',
        option_d: '芸術家の数が減少しているから',
        correct_answer: 'B',
        explanation: '最終段落に「著作権、芸術家の雇用、そして人間の存在意義にまで影響を及ぼす」と明記されている。',
      },
    ],
  },
  {
    title: '少子高齢化と社会保障の持続可能性',
    category: '社会',
    content: `日本は世界で最も急速に高齢化が進む国の一つである。2023年時点で総人口に占める65歳以上の割合は約29%に達しており、この趨勢は今後も続くと予測されている。一方、出生率は長年にわたって低下を続け、生産年齢人口の減少が深刻な問題となっている。

こうした人口構造の変化は、社会保障制度の財政的持続可能性に根本的な疑問を投げかけている。現在の社会保障制度は、現役世代が高齢者を支えるという「世代間扶養」の原理に基づいている。しかし、支える側の人口が減り、支えられる側が増え続ければ、制度の維持は困難となる。

政府はこの問題に対応すべく、様々な施策を講じてきた。定年延長による高齢者の就労促進、女性の社会参加支援、外国人労働者の受け入れ拡大などがその例として挙げられる。しかし、これらの施策が抜本的な解決策となり得るかどうかについては、専門家の間でも意見が分かれている。

少子高齢化は単なる経済問題ではない。それは地域コミュニティの衰退、文化・技術の継承、さらには国家のアイデンティティにまで及ぶ複合的な課題である。この問題への取り組みには、個々の施策を超えた、社会全体の価値観と制度の再設計が求められている。`,
    questions: [
      {
        question: '本文において「世代間扶養」とはどのような原理か？',
        option_a: '高齢者が若者を経済的に支援する仕組み',
        option_b: '現役世代が高齢者の生活を支える仕組み',
        option_c: '政府が全世代に平等に給付する仕組み',
        option_d: '家族が互いに介護し合う仕組み',
        correct_answer: 'B',
        explanation: '第二段落に「現役世代が高齢者を支えるという「世代間扶養」の原理」と明確に説明されている。',
      },
      {
        question: '筆者が少子高齢化を「複合的な課題」と述べた理由として最も適切なものはどれか？',
        option_a: '多くの政府部門が関与しているから',
        option_b: '経済・地域・文化・国家アイデンティティなど多方面に影響が及ぶから',
        option_c: '解決策が複数存在するから',
        option_d: '外国でも同様の問題が起きているから',
        correct_answer: 'B',
        explanation: '最終段落で「地域コミュニティの衰退、文化・技術の継承、さらには国家のアイデンティティにまで及ぶ複合的な課題」と述べられている。',
      },
      {
        question: '本文で政府の施策として挙げられていないものはどれか？',
        option_a: '定年延長',
        option_b: '女性の社会参加支援',
        option_c: '出生率向上のための直接補助金',
        option_d: '外国人労働者の受け入れ拡大',
        correct_answer: 'C',
        explanation: '第三段落では「定年延長、女性の社会参加支援、外国人労働者の受け入れ拡大」が挙げられているが、出生率向上のための直接補助金への言及はない。',
      },
    ],
  },
  {
    title: '言語と思考の関係',
    category: '言語学',
    content: `言語と思考の関係は、言語学者や哲学者が長年にわたって議論してきた問いである。私たちは言語を通じて考えるのか、それとも思考は言語とは独立して存在するのか。この問いに対する答えは、人間の認知と文化の本質に関わる重要な示唆を持っている。

サピア＝ウォーフ仮説として知られる言語相対論は、その極端な形において、言語が思考を規定するという考えを提唱する。すなわち、ある言語に特定の語彙や文法構造が存在しない場合、その言語の話者はその概念を思考することさえできないというのである。例えば、色の語彙が少ない言語の話者は、色の区別を認識する能力が劣るという研究結果も報告されている。

しかし、この仮説の強い形は現在では広く批判されている。実験的研究によれば、言語を持たない乳幼児や、手話を持たない聴覚障害者でも、複雑な論理的思考や数学的推論が可能であることが示されている。つまり、思考の基盤となる認知能力は言語とは独立して存在するという見方が有力である。

現在では、言語と思考は互いに独立しながらも深く影響し合う、という穏やかな相互作用説が主流となりつつある。言語は思考を制約するのではなく、思考をより精緻に、より効率的に行うための道具として機能するという解釈だ。`,
    questions: [
      {
        question: 'サピア＝ウォーフ仮説の極端な形が主張することは何か？',
        option_a: '言語は文化によって異なる',
        option_b: '言語が思考を規定し、言語なしには概念を思考できない',
        option_c: '思考は言語とは完全に独立している',
        option_d: '言語能力は遺伝によって決まる',
        correct_answer: 'B',
        explanation: '第二段落に「言語が思考を規定するという考えを提唱する。すなわち、ある言語に特定の語彙や文法構造が存在しない場合、その言語の話者はその概念を思考することさえできない」と説明されている。',
      },
      {
        question: '本文において、サピア＝ウォーフ仮説への反論として挙げられている証拠はどれか？',
        option_a: '多言語話者が複数の文化を理解できること',
        option_b: '言語を持たない乳幼児でも論理的思考が可能であること',
        option_c: '色の語彙が多い言語の話者の方が色の識別が優れていること',
        option_d: '手話が言語として認められていること',
        correct_answer: 'B',
        explanation: '第三段落で「言語を持たない乳幼児や、手話を持たない聴覚障害者でも、複雑な論理的思考や数学的推論が可能である」ことが仮説への反論として挙げられている。',
      },
    ],
  },
];
